name: Build Flowdy

on:
  workflow_dispatch:

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Stáhnutí kódu
        uses: actions/checkout@v4

      - name: Instalace Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalace Rustu
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'ubuntu-latest' && 'aarch64-linux-android' || '' }}

      - name: Instalace Javy a Android SDK
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android NDK
        if: matrix.platform == 'ubuntu-latest'
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Accept Android Licenses
        if: matrix.platform == 'ubuntu-latest'
        run: yes | sdkmanager --licenses || true

      - name: Instalace NPM balíčků
        run: npm install

      - name: Sestavení aplikací
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v0.2.6
          releaseName: 'Flowdy v0.2.6'
          releaseDraft: true
          prerelease: false
          # Změna: PATH nastavujeme přímo v argumentu pro Linux, aby se nepoškodilo globální ENV
          args: ${{ matrix.platform == 'ubuntu-latest' && format('--target aarch64-linux-android --bundle-path-env PATH={0}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH', steps.setup-ndk.outputs.ndk-path) || '' }}